language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - export DATABASE_URL=postgres://qnqsxowzttamrj:0718a669df8e9589411bc684df46efab54b9ded3b4bec20ae6d0e25b5e373d38@ec2-54-225-97-112.compute-1.amazonaws.com:5432/d883mkmotls2c0
  - export PYTHONPATH=/home/travis/build/malfahad/fast-food-fast
  - pytest --cov=$PYTHONPATH 
after_success:
  - coveralls
